don't load the mongorc file to call db.isMaster()
Since commit #fbfab02e4e, the code fails when authentication is enabled and
the admin user is not created yet. This is due to the simplification
performed, awaiting for a boolean value, whereas it produce such result :

Error: Authentication failed.
true